export const TYPES: string[] = [
  "Armor Plating",
  "Arrows",
  "Belly Bow",
  "Bow",
  "Cloth Armor",
  "Construction Addition",
  "Engineering Accessory",
  "Fire Pot",
  "Fishing Nets",
  "Great Axe",
  "Heavy Spear",
  "Holy Staff",
  "Javelin",
  "Laborer Gear",
  "Light Armor",
  "Light Spear",
  "Medium Armor",
  "Merchant Gear",
  "Ram Head",
  "Reinforced Construction",
  "Religious Item",
  "Scepter",
  "Scout Special",
  "Shield",
  "Ship Accessory",
  "Sling",
  "Soldiers' Gear",
  "Sword",
  "Throwing Arm",
  "Torc",
  "Vanity Helm",
  "Vanity Shield",
  "Vanity Weapon",
  "War Horn",
  "Warpaint",
  "Work Tools",
]
