export const vendorLocations: {
  [id: string]: string,
} = {
  A01_Cap_BasicStore01: "Delos",
  A02_Cap_BasicStore01: "Farafra Oasis",
  A03_Cap_BasicStore01: "Carthage",
  At_Cap_BasicStore01: "Athens",
  Ba_Cap_BasicStore01: "Babylonian Capital City",
  Ba_Cap_BasicStoreBabylon01: "Blueprint, Advanced Recipe Store",
  Ba_Cap_BasicStoreBabylon02: "Blueprint, Advanced General Store",
  Ba_Cap_BasicStoreBabylon05: "Blueprint, Advanced Crafting Store",
  Ba_Cap_StoreStore01: "Babylonian Capital City",
  Ce_Cap_BasicStore01: "Celtic Capital City",
  Ce_Cap_BasicStoreMassalia01: "Massalia",
  Ce_Cap_BasicStoreMassalia02: "Massalia",
  Ce_Cap_BasicStoreMassalia03: "Massalia",
  Ce_Cap_BasicStoreMassalia04: "Massalia",
  Ce_Cap_BasicStoreMassalia05: "Massalia",
  Ce_Cap_StoreStore01: "Celtic Capital City",
  Cy_Cap_BasicStore01: "Cyprus",
  Cy_Cap_BasicStore02: "Cyprus",
  Cy_Cap_BasicStore03: "Cyprus",
  Eg_Cap_BasicStore01: "Egyptian Capital City",
  Eg_Cap_BasicStoreNubia01: "Nubian Expedition",
  Eg_Cap_BasicStoreNubia02: "Nubian Expedition",
  Eg_Cap_BasicStoreNubia03: "Nubian Expedition",
  Eg_Cap_BasicStoreNubia04: "Nubian Expedition",
  Eg_Cap_BasicStoreNubia05: "Nubian Expedition",
  Eg_Cap_StoreStore01: "Egyptian Capital City",
  Gn_Cap_BasicStoreBabylon01: "Babylon",
  Gn_Cap_BasicStoreBabylon02: "Babylon",
  Gn_Cap_EP_VanityStore01: "Vanity Island",
  Gn_Cap_EP_VanityStore02: "Vanity Island",
  Gn_Cap_EP_VanityStore03: "Vanity Island",
  Gn_Cap_GeneralEmpireStore01: "Capital City",
  gn_Cap_LootStore01: "Blueprint, Uncommon Defenses",
  gn_Cap_LootStore02: "Blueprint, Uncommon Armaments",
  gn_Cap_LootStore03: "Blueprint, Respectable Rare Ramparts",
  gn_Cap_LootStore04: "Blueprint, Reputable Rare Rewards",
  gn_Cap_LootStore05: "Blueprint, Elegant Epic Escutcheons",
  gn_Cap_LootStore06: "Blueprint, Exquisite Epic Edges",
  gn_Cap_LootStore08: "Blueprint, Sturdy Staves and Slings",
  Gn_Cap_PawnShop_01: "Blueprint, Moe's Mystorium",
  Gn_Cap_PawnShop_02: "Sparta",
  Gn_Cap_PDLC_Store: "Capital City",
  Gn_Cap_RetailStore01: "Blueprint, Windy's Wild Widgets",
  Gn_Cap_VanityGearStore01: "Vanity Island",
  Gn_Cap_VanityGearStore02: "Vanity Island",
  Gn_Cap_VanityGearStore03: "Vanity Island",
  gn_Cap_VanityStore01: "Blueprint, Startling Statuary",
  gn_Cap_VanityStore02: "Blueprint, Glorious Gardening",
  gn_Cap_VanityStore03: "Blueprint, Ornate Ornaments",
  gn_Cap_VanityStore04: "Blueprint, Bountiful Bushes",
  Gn_Cap_VanityStore05: "Blueprint, Tantalizing Topiary",
  Gn_Cap_VanityStore06: "Vanity Island",
  Gn_SpartaSpecialStore01: "Sparta",
  Gr_Cap_BasicStore01: "Greek Capital City",
  Gr_Cap_BasicStoreArgos01: "Argos",
  Gr_Cap_BasicStoreArgos02: "Argos",
  Gr_Cap_BasicStoreArgos03: "Argos",
  Gr_Cap_BasicStoreArgos04: "Argos",
  Gr_Cap_BasicStoreArgos05: "Argos",
  Gr_Cap_BasicStoreArgos06: "Argos",
  Gr_Cap_BasicStoreArgos07: "Argos",
  Gr_Cap_BasicStoreMycenae01: "Mycenae",
  Gr_Cap_BasicStoreMycenae02: "Mycenae",
  Gr_Cap_BasicStoreMycenae03: "Mycenae",
  Gr_Cap_BasicStoreMycenae04: "Mycenae",
  Gr_Cap_BasicStoreMycenae05: "Mycenae",
  Gr_Cap_StoreStore01: "Greek Capital City",
  Mn_Cap_BasicStore01: "Crete",
  Mn_Cap_BasicStore02: "Crete",
  Mn_Cap_BasicStore03: "Crete",
  Nh_Cap_BasicStore01: "Northern Hold",
  Nh_Cap_BasicStore02: "Northern Hold",
  Nh_Cap_BasicStore03: "Northern Hold",
  No_Cap_BasicStore01: "Norse Capital City",
  No_Cap_BasicStoreNorse01: "Blueprint, Advanced Recipe Store",
  No_Cap_BasicStoreNorse02: "Blueprint, Advanced General Store",
  No_Cap_BasicStoreNorse05: "Blueprint, Advanced Crafting Store",
  No_Cap_StoreStore01: "Norse Capital City",
  Pe_Cap_BasicStore01: "Persian Capital City",
  Pe_Cap_BasicStorePersia01: "Blueprint, Advanced Recipe Store",
  Pe_Cap_BasicStorePersia02: "Blueprint, Advanced General Store",
  Pe_Cap_BasicStorePersia05: "Blueprint, Advanced Crafting Store",
  Pe_Cap_StoreStore01: "Persian Capital City",
  Pv_Cap_BasicStoreSparta01: "Sparta",
  Pv_Cap_BasicStoreSparta02: "Sparta",
  Pv_Cap_BasicStoreSparta03: "Sparta",
  Pv_Cap_BasicStoreSparta04: "Sparta",
  Wu_Cap_BasicStore01: "Well of Urd",
}
