export const vendorLocations: {
  [id: string]: string,
} = {
  a01_cap_basicstore01: "Delos",
  a02_cap_basicstore01: "Farafra Oasis",
  a03_cap_basicstore01: "Carthage",
  at_cap_basicstore01: "Athens",
  ba_cap_basicstore01: "Babylonian Capital City",
  ba_cap_basicstorebabylon01: "Blueprint, Advanced Recipe Store",
  ba_cap_basicstorebabylon02: "Blueprint, Advanced General Store",
  ba_cap_basicstorebabylon05: "Blueprint, Advanced Crafting Store",
  ba_cap_storestore01: "Babylonian Capital City",
  ce_cap_basicstore01: "Celtic Capital City",
  ce_cap_basicstoremassalia01: "Massalia",
  ce_cap_basicstoremassalia02: "Massalia",
  ce_cap_basicstoremassalia03: "Massalia",
  ce_cap_basicstoremassalia04: "Massalia",
  ce_cap_basicstoremassalia05: "Massalia",
  ce_cap_storestore01: "Celtic Capital City",
  cy_cap_basicstore01: "Cyprus",
  cy_cap_basicstore02: "Cyprus",
  cy_cap_basicstore03: "Cyprus",
  eg_cap_basicstore01: "Egyptian Capital City",
  eg_cap_basicstorenubia01: "Nubian Expedition",
  eg_cap_basicstorenubia02: "Nubian Expedition",
  eg_cap_basicstorenubia03: "Nubian Expedition",
  eg_cap_basicstorenubia04: "Nubian Expedition",
  eg_cap_basicstorenubia05: "Nubian Expedition",
  eg_cap_storestore01: "Egyptian Capital City",
  gn_cap_basicstorebabylon01: "Babylon",
  gn_cap_basicstorebabylon02: "Babylon",
  gn_cap_ep_vanitystore01: "Vanity Island",
  gn_cap_ep_vanitystore02: "Vanity Island",
  gn_cap_ep_vanitystore03: "Vanity Island",
  gn_cap_generalempirestore01: "Capital City",
  gn_cap_lootstore01: "Blueprint, Uncommon Defenses",
  gn_cap_lootstore02: "Blueprint, Uncommon Armaments",
  gn_cap_lootstore03: "Blueprint, Respectable Rare Ramparts",
  gn_cap_lootstore04: "Blueprint, Reputable Rare Rewards",
  gn_cap_lootstore05: "Blueprint, Elegant Epic Escutcheons",
  gn_cap_lootstore06: "Blueprint, Exquisite Epic Edges",
  gn_cap_lootstore08: "Blueprint, Sturdy Staves and Slings",
  gn_cap_pawnshop_01: "Blueprint, Moe's Mystorium",
  gn_cap_pawnshop_02: "Sparta",
  gn_cap_pdlc_store: "Capital City",
  gn_cap_retailstore01: "Blueprint, Windy's Wild Widgets",
  gn_cap_vanitygearstore01: "Vanity Island",
  gn_cap_vanitygearstore02: "Vanity Island",
  gn_cap_vanitygearstore03: "Vanity Island",
  gn_cap_vanitystore01: "Blueprint, Startling Statuary",
  gn_cap_vanitystore02: "Blueprint, Glorious Gardening",
  gn_cap_vanitystore03: "Blueprint, Ornate Ornaments",
  gn_cap_vanitystore04: "Blueprint, Bountiful Bushes",
  gn_cap_vanitystore05: "Blueprint, Tantalizing Topiary",
  gn_cap_vanitystore06: "Vanity Island",
  gn_spartaspecialstore01: "Sparta",
  gr_cap_basicstore01: "Greek Capital City",
  gr_cap_basicstoreargos01: "Argos",
  gr_cap_basicstoreargos02: "Argos",
  gr_cap_basicstoreargos03: "Argos",
  gr_cap_basicstoreargos04: "Argos",
  gr_cap_basicstoreargos05: "Argos",
  gr_cap_basicstoreargos06: "Argos",
  gr_cap_basicstoreargos07: "Argos",
  gr_cap_basicstoremycenae01: "Mycenae",
  gr_cap_basicstoremycenae02: "Mycenae",
  gr_cap_basicstoremycenae03: "Mycenae",
  gr_cap_basicstoremycenae04: "Mycenae",
  gr_cap_basicstoremycenae05: "Mycenae",
  gr_cap_storestore01: "Greek Capital City",
  mn_cap_basicstore01: "Crete",
  mn_cap_basicstore02: "Crete",
  mn_cap_basicstore03: "Crete",
  nh_cap_basicstore01: "Northern Hold",
  nh_cap_basicstore02: "Northern Hold",
  nh_cap_basicstore03: "Northern Hold",
  no_cap_basicstore01: "Norse Capital City",
  no_cap_basicstorenorse01: "Blueprint, Advanced Recipe Store",
  no_cap_basicstorenorse02: "Blueprint, Advanced General Store",
  no_cap_basicstorenorse05: "Blueprint, Advanced Crafting Store",
  no_cap_storestore01: "Norse Capital City",
  pe_cap_basicstore01: "Persian Capital City",
  pe_cap_basicstorepersia01: "Blueprint, Advanced Recipe Store",
  pe_cap_basicstorepersia02: "Blueprint, Advanced General Store",
  pe_cap_basicstorepersia05: "Blueprint, Advanced Crafting Store",
  pe_cap_storestore01: "Persian Capital City",
  pv_cap_basicstoresparta01: "Sparta",
  pv_cap_basicstoresparta02: "Sparta",
  pv_cap_basicstoresparta03: "Sparta",
  pv_cap_basicstoresparta04: "Sparta",
  wu_cap_basicstore01: "Well of Urd",
}
